---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description (Simple parameter)
    Type: String
  SecurityGroupPort:
    Description: Simple Description of a Number Parameter, with MinValue and MaxValue
    Type: Number
    MinValue: 1150
    MaxValue: 65535
  InstaceType:
    Description: WebServer Ec2 Instance type ( has default, Allowed Values )
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SecurityGroupIngressCIDR:
    Description: The IP address range that can be used to communicate to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DbSubnetIpBlocks:
    Description: "Comma-delimited list of three CIDR blocks"
    Type: CommaDelimitedList
    Default: "10.0.48.0/24, 10.0.112.0/24, 10.0.176.0/24"

# Our Ec2 Instance
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-0568773882d492fc8
      InstanceType: !Ref InstaceType
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      Tags:
        - Key: Name
          Value : My-Test-EC2

# Our Ec2 Security Group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH Access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: !Ref SecurityGroupPort
        IpProtocol: tcp
        ToPort: !Ref SecurityGroupPort



# Our Ec2 Security Group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Connection form specified CIDR ranges
      SecurityGroupIngress:
      - CidrIp: !Ref DbSubnetIpBlocks
        FromPort: !Ref SecurityGroupPort
        IpProtocol: tcp
        ToPort: !Ref SecurityGroupPort
      - CidrIp: !Ref DbSubnetIpBlocks
        FromPort: !Ref SecurityGroupPort
        IpProtocol: tcp
        ToPort: !Ref SecurityGroupPort


# Our Elastic IP for Instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance
